name: Deploy Express WebSocket App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Start Express app
        run: |
          npm start &
          sleep 5

      - name: Expose app with ngrok
        run: |
          ./ngrok http 8080 --region=us --authtoken=2uA3QtM3vZatHsQAqSeILAenhhd_4qd6K31LpyeVD18fAqMGL
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
