name: Deploy Express WebSocket App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install latest ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          ./ngrok authtoken 2uA3QtM3vZatHsQAqSeILAenhhd_4qd6K31LpyeVD18fAqMGL
          ./ngrok http 8080 --region=us
        env:
          NGROK_TOKEN: 2uA3QtM3vZatHsQAqSeILAenhhd_4qd6K31LpyeVD18fAqMGL

      - name: Start Express app
        run: |
          npm start &
          sleep 5

      - name: Expose app with ngrok
        run: |
          ngrok http 8080 --region=us
