name: Deploy Express WebSocket AppsS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start Express app
        run: |
          npm start &
          sleep 5

      - name: Expose app with ngrok
        uses: ngrok/ngrok@v3
        env:
          NGROK_TOKEN: 2uA3QtM3vZatHsQAqSeILAenhhd_4qd6K31LpyeVD18fAqMGLv
          NGROK_REGION: us
          NGROK_PORT: 8080