name: Deploy Express WebSocket App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start Express app
        run: |
          npm start &
          sleep 5

      - name: Expose app with ngrok
        uses: ngrok/ngrok@1.0.0
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          NGROK_PORT: 8080
